name: Schoolinka Blog CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x, 18.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #   - name: Use Node.js version 18.17.1
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - run: npm install --force
