name: Schoolinka Blog CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  integration-test:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    strategy:
      matrix:
        node-version: [14.x, 18.x]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD:
            postgres
            # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST:
            postgres
            # The default PostgreSQL port
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      # - name: use Node.js version 18.17.1
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - run: npm install --force
      - run: npm test
