name: Schoolinka Blog CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x, 18.x]
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: localUser
          POSTGRES_PASSWORD: localPassword
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
        # - name: Use Node.js version 18.17.1
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - run: npm install --force
      - run: npm test
